yolo_model:

  config_file:
    name: yolov3-tiny-drive.cfg
  weight_file:
    name: yolov3-tiny-drive.weights
    # name: yolov3-tiny-dp_last.weights
    # name: yolov3-tiny-dp_best.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - turn
      - road_construction
      - crossing
      - bus
      - stop
