yolo_model:

  config_file:
    name: yolov3-tiny-gesture.cfg
  weight_file:
    name: yolov3-tiny-gesture.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - 0-hand
      - 1-hand
      - 2-hand
      - 3-hand
      - 4-hand
      - 5-hand
     
